# 异常

Activiti 基Exception 是`org.activiti.engine.ActivitiException` ,一个非受检异常
,这个异常可能会在使用 API 的时候抛出,指定的异常类型往往会在 javadocs 里面声明,例如:
`TaskService`中的一个方法:

```java
/**
 * Called when the task is successfully executed.
 * @param taskId the id of the task to complete, cannot be null.
 * @throws ActivitiObjectNotFoundException when no task exists with the given id.
 */
 void complete(String taskId);
```

上面的例子会抛出`ActivitiIllegalArgumentException `

Activiti 中的异常全部是运行时异常

![](https://www.showdoc.cc/server/api/common/visitfile/sign/16e702faa4d3172a6aa4173a79622065?showdoc=.jpg)

- ActivitiException (org.activiti.engine)
  - ActivitiClassLoadingException (org.activiti.engine) 加载类异常
  - ActivitiIllegalArgumentException (org.activiti.engine) 非法参数异常
  - ActivitiObjectNotFoundException (org.activiti.engine) 操作对象不存在
    - JobNotFoundException (org.activiti.engine) 操作Job对象不存在
  - ActivitiOptimisticLockingException (org.activiti.engine) 并发导致乐观锁异常
  - ActivitiTaskAlreadyClaimedException (org.activiti.engine)任务被重新声明代理人
  - ActivitiWrongDbException (org.activiti.engine) 引擎与数据库版本不匹配
  - BpmnError (org.activiti.engine.delegate)定义业务异常,控制流程

